### ISSUE TITLE
Add HTML Report plugin to Jenkins

### ISSUE THREAD

**Issue by Skytrace** [Skytrace/aqa-hryvna-ua#19]
I have proposal to add jenkins [plugin](https://wiki.jenkins.io/display/JENKINS/HTML+Publisher+Plugin) to display Allure Report.

**Comment by YaroslavDiachenko** [comment]
![allure-jenkins](https://user-images.githubusercontent.com/29801434/50976439-a4bff800-14f8-11e9-8d1d-89bd43b50016.png)

**Comment by YaroslavDiachenko** [comment]
![allure-jenkins-2](https://user-images.githubusercontent.com/29801434/50976731-57905600-14f9-11e9-9060-045aa2167e61.png)
