### ISSUE TITLE
Add Allure report in TAF

### ISSUE THREAD

**Issue by Skytrace** [Skytrace/aqa-hryvna-ua#5]

**Comment by Skytrace** [comment]
For now we have a basic TAF structure with first test, my congratulations!
Now, will be nice to have some report/chart system for checking our tests. I propose to use Allure chart system. On this chart, we will be able easy to check our tests statuses on few kind of chart's.

**Comment by YaroslavDiachenko** [comment]
![allure_report_screen_1](https://user-images.githubusercontent.com/29801434/49725139-b00ed200-fc73-11e8-8fd4-d132ec0c9b1a.png)
![allure_report_screen_2](https://user-images.githubusercontent.com/29801434/49725155-ba30d080-fc73-11e8-9528-4df524e50e22.png)

**Comment by YaroslavDiachenko** [comment]
branch 'allure-report'
